In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(77)
layers = tf.contrib.layers

tf.reset_default_graph() # tensorboard graph reset

Instructions for updating:
Use the retry module or similar alternatives.


In [11]:
a = tf.zeros([5,2,3,4])
b = tf.unstack(a)
print (a)
print (b)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print (np.shape(sess.run(a)))
    print (np.shape(sess.run(b)))

Tensor("zeros_7:0", shape=(5, 2, 3, 4), dtype=float32)
[<tf.Tensor 'unstack_7:0' shape=(2, 3, 4) dtype=float32>, <tf.Tensor 'unstack_7:1' shape=(2, 3, 4) dtype=float32>, <tf.Tensor 'unstack_7:2' shape=(2, 3, 4) dtype=float32>, <tf.Tensor 'unstack_7:3' shape=(2, 3, 4) dtype=float32>, <tf.Tensor 'unstack_7:4' shape=(2, 3, 4) dtype=float32>]
(5, 2, 3, 4)
(5, 2, 3, 4)


In [18]:
x = "22 21 22 21 22 17 22 15 15 15  10 14 22 21 22 21 22 17 22 15  15 15 10 14 22 21 22 22 10 21  22 22 10 17 22 22 10 15 10 14  15 17 14 12 10 09 10 10 05 10  12 14 14 15 17 15 14 12 22 21  22 22 10 21 22 22 10 17 22 22  10 15 10 14 15 17 26 24 17 24  22 21 22 10 12 14 05 10 14 15  17 05 14 15 13 12 22 24 22 21  22 10 17 10 22 24 22 21 22 10  17 10 22 24 22 21 22 24 26 27  29 26 24 22 21 12 22 26 22 21  22 10 17 10 22 24 22 21 22 10  17 10 22 24 22 21 22 24 26 27  29 26 24 22 21 12 22 22 21 22  10 17 10 22 22 20 22 10 17 10  22 22 20 22 24 25 27 29 25 24  22 20 12 22 24 22 20 22 10 17  10 22 24 22 20 22 10 17 10 22  24 22 20 22 20 22 22 10 20 22  22 10 17 22 22 10 15 10 13 15  17 13 12 10 08 10 10 05 10 12  13 05 10 12 13 05 12 13 17 05  13 15 17 05 15 13 12 05 15 13  12 08 22 20 22 22 10 20 22 22  10 17 22 22 10 15 10 13 15 17  25 24 17 24 22 20 22 10 12 13  05 10 12 13 05 13 15 17 05 13  15 17 05 15 13 12 05 08 12 22  24 22 20 22 10 17 10 22 22 20  22 10 17 10 22 22 20 22 24 25  27 29 25 24 22 20 10 17 10 22  24 22 20 22 10 17 10 22 24 22  20 22 10 17 10 22 22 20 22 24  25 27 29 25 24 22 20 12 17 12  22 24 22 20 22 10 17 10 22 24  22 20 22 10 17 10 22 22 20 22  24 25 27 29 25 24 22 20 12 22  10 17 10 22 22 20 22 24 25 27  29 25 24 22 20 12 08 05 22 20  22 20 22 17 22 15 13 15 17 13  12 10 08 10 05 10 12 13 05 10  13 15 17 05 13 15 13 12 08 10  13 22 20 22 20 22 17 22 15 13  15 17 25 24 10 08 10 10 12 13  05 10 13 15 17 05 10 15 13 12"

m = x.split()[:160]
m = [int(a) for a in m]
print (m)
print (len(m))

dic = [{'name':'River flows in you', 'melody':m}, 0]
print (dic[0]['melody'])

[22, 21, 22, 21, 22, 17, 22, 15, 15, 15, 10, 14, 22, 21, 22, 21, 22, 17, 22, 15, 15, 15, 10, 14, 22, 21, 22, 22, 10, 21, 22, 22, 10, 17, 22, 22, 10, 15, 10, 14, 15, 17, 14, 12, 10, 9, 10, 10, 5, 10, 12, 14, 14, 15, 17, 15, 14, 12, 22, 21, 22, 22, 10, 21, 22, 22, 10, 17, 22, 22, 10, 15, 10, 14, 15, 17, 26, 24, 17, 24, 22, 21, 22, 10, 12, 14, 5, 10, 14, 15, 17, 5, 14, 15, 13, 12, 22, 24, 22, 21, 22, 10, 17, 10, 22, 24, 22, 21, 22, 10, 17, 10, 22, 24, 22, 21, 22, 24, 26, 27, 29, 26, 24, 22, 21, 12, 22, 26, 22, 21, 22, 10, 17, 10, 22, 24, 22, 21, 22, 10, 17, 10, 22, 24, 22, 21, 22, 24, 26, 27, 29, 26, 24, 22, 21, 12, 22, 22, 21, 22]
160
[22, 21, 22, 21, 22, 17, 22, 15, 15, 15, 10, 14, 22, 21, 22, 21, 22, 17, 22, 15, 15, 15, 10, 14, 22, 21, 22, 22, 10, 21, 22, 22, 10, 17, 22, 22, 10, 15, 10, 14, 15, 17, 14, 12, 10, 9, 10, 10, 5, 10, 12, 14, 14, 15, 17, 15, 14, 12, 22, 21, 22, 22, 10, 21, 22, 22, 10, 17, 22, 22, 10, 15, 10, 14, 15, 17, 26, 24, 17, 24, 22, 21, 22, 10, 12, 14, 5, 10, 14, 15, 1

In [21]:
a = np.array([5,5,5,10,10])
a = a.reshape(1,5)
print (a)
print (a.shape)
x = tf.Variable(a, tf.int16)
dec_input = tf.slice(x, [0,1], [1, 4])

y = tf.concat([tf.zeros([1, 1], tf.int64), dec_input], 1)
dec_input2 = tf.concat([tf.zeros([1,1], tf.int64), tf.reverse(dec_input, [1])],1)

print (dec_input)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print (sess.run(dec_input))
    print (sess.run(dec_input2))

[[ 5  5  5 10 10]]
(1, 5)
Tensor("Slice_16:0", shape=(1, 4), dtype=int64)
[[ 5  5 10 10]]
[[ 0 10 10  5  5]]


In [19]:
aaa = np.ones([2, 160, 128])
print (aaa.shape)
ass = np.reshape(aaa, [-1, 128])
print (ass.shape)

(2, 160, 128)
(320, 128)


In [14]:
a = [[2,3,4],[1,2,3]]

v = tf.Variable(a, tf.int16)
w = tf.one_hot(v, 5)

r = tf.slice(v, [0,1], [2,2])
z = tf.zeros([2,1], tf.int32)
rz = tf.concat([z, r], 1)
rr = tf.reverse(rz, [1])

b=tf.concat([tf.zeros([2, 1], tf.int32), tf.reverse(r, [1])], 1)
b_one = tf.one_hot(b,5)
b_re = tf.transpose(b_one, perm = [1,0,2])

print (np.shape(v))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print (sess.run(v))
    print (sess.run(w))
    print (sess.run(tf.shape(w)))
    print (sess.run(w[:][:][0]))
    print (sess.run(r))
    print (sess.run(rz))
    print (sess.run(rr))
    print (sess.run(z))
    print (sess.run(b))
    print (sess.run(b_one))
    print (sess.run(b_re))
    print (sess.run(b_re[0]))

(2, 3)
[[2 3 4]
 [1 2 3]]
[[[ 0.  0.  1.  0.  0.]
  [ 0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  1.]]

 [[ 0.  1.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.]
  [ 0.  0.  0.  1.  0.]]]
[2 3 5]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[[3 4]
 [2 3]]
[[0 3 4]
 [0 2 3]]
[[4 3 0]
 [3 2 0]]
[[0]
 [0]]
[[0 4 3]
 [0 3 2]]
[[[ 1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.]
  [ 0.  0.  0.  1.  0.]]

 [[ 1.  0.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.]
  [ 0.  0.  1.  0.  0.]]]
[[[ 1.  0.  0.  0.  0.]
  [ 1.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  1.]
  [ 0.  0.  0.  1.  0.]]

 [[ 0.  0.  0.  1.  0.]
  [ 0.  0.  1.  0.  0.]]]
[[ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]


In [40]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])
print (np.shape(t))
a = tf.slice(t, [1, 0, 0], [2, 2, 3])  # [[[3, 3, 3]]]
b = tf.slice(t, [1, 0, 0], [1, 2, 3])  # [[[3, 3, 3],
                                   #   [4, 4, 4]]]
c = tf.slice(t, [1, 0, 0], [2, 1, 3])  # [[[3, 3, 3]],
                                   #  [[5, 5, 5]]]
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print (sess.run(a))
    #print (sess.run(b))
    #print (sess.run(c))
    
    print (sess.run(t[0,0,0]))

(3, 2, 3)
[[[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
1


In [12]:
melody_sample = list(range(1,37))
melody_sample.append(50)
idx2char = list(set(melody_sample))
char2idx = {c:i for i, c in enumerate(idx2char)}

batch_size = 2

melody = [50, 10, 17, 17, 17, 15, 13,  17, 17, 17, 17, 17, 15, 13,  17, 50, 17, 17, 15, 13,  17, 17, 17, 17, 15, 17, 15, 13,   10, 10, 17, 17, 17, 17, 15, 13,  17, 50, 17, 15, 17, 15, 13,  20, 50, 17, 17, 17, 15, 13,  17, 15, 15, 15, 15, 17, 15, 13,   10, 22, 22, 50, 10, 10, 13,  10, 22, 22, 50, 22, 22, 22,  20, 50, 20, 20, 20, 25, 24,  20, 50, 17, 15, 13,   10, 22, 22, 50, 10, 10, 13,  10, 22, 22, 50, 22, 22, 22,  20, 50, 20, 20, 20, 25, 24,  25, 24, 50, 17, 20,   22, 22, 17, 20, 17, 20,  22, 22, 20, 25, 25, 24, 25,  20, 50, 20, 25, 25, 24, 25,  29, 27, 25, 24, 20,   22, 22, 17, 20, 17, 20,  22, 22, 20, 25, 25, 24, 25,  20, 50, 20, 25, 25, 24, 25,  29, 27, 25, 24, 24]
rhythm = [2, 2, 2, 2, 4, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 4, 2, 2,  2, 2, 2, 2, 2, 2, 2, 2,   2, 2, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  2, 2, 2, 2, 2, 2, 2, 2,   4, 3, 1, 2, 2, 2, 2,  4, 3, 1, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  8, 2, 2, 2, 2,   4, 3, 1, 2, 2, 2, 2,  4, 3, 1, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  2, 6, 4, 2, 2,  4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 4, 4, 2, 2,   4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 4, 4, 2, 2,]
# set sample song data (Roly Poly)
train_melody = []
train_melody.append(melody)
train_melody.append(rhythm)

def data2idx(data):
    x_data = []
    y_data = []
    for d in data:
        train_data = [char2idx[i] for i in d]
        x_data.append(train_data[:-1])
        y_data.append(train_data[1:])

    x_data = np.array(x_data)
    y_data = np.array(y_data)
    print (x_data.shape)
    return x_data, y_data

x_data, y_data = data2idx(train_melody)
print (x_data)
print (x_data.shape)

x_data = np.reshape(x_data, [batch_size, x_data.shape[1]])
y_data = np.reshape(y_data, [batch_size, y_data.shape[1]])

print (x_data.shape[1])

(2, 159)
[[36  9 16 16 16 14 12 16 16 16 16 16 14 12 16 36 16 16 14 12 16 16 16 16
  14 16 14 12  9  9 16 16 16 16 14 12 16 36 16 14 16 14 12 19 36 16 16 16
  14 12 16 14 14 14 14 16 14 12  9 21 21 36  9  9 12  9 21 21 36 21 21 21
  19 36 19 19 19 24 23 19 36 16 14 12  9 21 21 36  9  9 12  9 21 21 36 21
  21 21 19 36 19 19 19 24 23 24 23 36 16 19 21 21 16 19 16 19 21 21 19 24
  24 23 24 19 36 19 24 24 23 24 28 26 24 23 19 21 21 16 19 16 19 21 21 19
  24 24 23 24 19 36 19 24 24 23 24 28 26 24 23]
 [ 1  1  1  1  3  1  1  3  1  1  1  1  1  1  3  1  1  3  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  3  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  3  2  0  1  1  1  1  3  2  0  1  1  1  1
   3  1  1  1  1  1  1  7  1  1  1  1  3  2  0  1  1  1  1  3  2  0  1  1
   1  1  3  1  1  1  1  1  1  1  5  3  1  1  3  3  1  1  1  1  3  1  1  1
   1  1  1  3  1  1  1  1  1  1  3  3  3  1  1  3  3  1  1  1  1  3  1  1
   1  1  1  1  3  1  1  1  1  1  1  3  3  3  1]]
(2, 15

In [2]:
melody_sample = list(range(1,37))
melody_sample.append(50)
idx2char = list(set(melody_sample))
char2idx = {c:i for i, c in enumerate(idx2char)}

print(melody_sample)
print(idx2char)
print(char2idx)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 50]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 50]
{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11, 13: 12, 14: 13, 15: 14, 16: 15, 17: 16, 18: 17, 19: 18, 20: 19, 21: 20, 22: 21, 23: 22, 24: 23, 25: 24, 26: 25, 27: 26, 28: 27, 29: 28, 30: 29, 31: 30, 32: 31, 33: 32, 34: 33, 35: 34, 36: 35, 50: 36}


In [3]:
# melody : [50, 10, 17, 17, 17, 15, 13,  17, 17, 17, 17, 17, 15, 13,  17, 50, 17, 17, 15, 13,  17, 17, 17, 17, 15, 17, 15, 13,   10, 10, 17, 17, 17, 17, 15, 13,  17, 50, 17, 15, 17, 15, 13,  20, 50, 17, 17, 17, 15, 13,  17, 15, 15, 15, 15, 17, 15, 13,   10, 22, 22, 50, 10, 10, 13,  10, 22, 22, 50, 22, 22, 22,  20, 50, 20, 20, 20, 25, 24,  20, 50, 17, 15, 13,   10, 22, 22, 50, 10, 10, 13,  10, 22, 22, 50, 22, 22, 22,  20, 50, 20, 20, 20, 25, 24,  25, 24, 50, 17, 20,   22, 22, 17, 20, 17, 20,  22, 22, 20, 25, 25, 24, 25,  20, 50, 20, 25, 25, 24, 25,  29, 27, 25, 24, 20,   22, 22, 17, 20, 17, 20,  22, 22, 20, 25, 25, 24, 25,  20, 50, 20, 25, 25, 24, 25,  29, 27, 25, 24, 24]
# rhythm : [2, 2, 2, 2, 4, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 4, 2, 2,  2, 2, 2, 2, 2, 2, 2, 2,   2, 2, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  2, 2, 2, 2, 2, 2, 2, 2,   4, 3, 1, 2, 2, 2, 2,  4, 3, 1, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  8, 2, 2, 2, 2,   4, 3, 1, 2, 2, 2, 2,  4, 3, 1, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  2, 6, 4, 2, 2,  4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 4, 4, 2, 2,   4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 4, 4, 2, 2,]
train_melody = [2, 2, 2, 2, 4, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 4, 2, 2,  2, 2, 2, 2, 2, 2, 2, 2,   2, 2, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  2, 2, 2, 2, 2, 2, 2, 2,   4, 3, 1, 2, 2, 2, 2,  4, 3, 1, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  8, 2, 2, 2, 2,   4, 3, 1, 2, 2, 2, 2,  4, 3, 1, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  2, 6, 4, 2, 2,  4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 4, 4, 2, 2,   4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,  4, 2, 2, 2, 2, 2, 2,  4, 4, 4, 2, 2,]
train_data = [char2idx[i] for i in train_melody]
x_data = train_data[:-1]
y_data = train_data[1:]
print (np.shape(train_melody[1:]))
print (np.shape(train_data))
print (np.shape(x_data))
print (np.shape(y_data))

(159,)
(160,)
(159,)
(159,)


In [4]:
input_size = len(char2idx) # 37
hidden_size = 128
output_size = len(char2idx) # 37
batch_size = 1
sequence_length = len(x_data)
learning_rate = 0.001

x_data = np.reshape(x_data, [batch_size, len(x_data)])
y_data = np.reshape(y_data, [batch_size, len(y_data)])

print (np.shape(x_data))
print (np.shape(y_data))

(1, 159)
(1, 159)


### Build a RNN model

In [5]:
X = tf.placeholder(tf.int32, [None, sequence_length], name = 'x_data')
Y = tf.placeholder(tf.int32, [None, sequence_length], name = 'y_data')
# one_hot : [sequence_length, input_size]
x_one_hot = tf.one_hot(X, input_size) 

with tf.variable_scope("RNN"):
    
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size,
                                                       state_is_tuple=True)

    # defining initial state
    initial_state = cell.zero_state(batch_size, dtype=tf.float32)

    outputs, state = tf.nn.dynamic_rnn(cell=cell,
                                                       inputs=x_one_hot,
                                                       initial_state=initial_state)
    # output size : [batch_size, seqence_length, hidden_size]
    X_for_fc = tf.reshape(outputs, [-1, hidden_size])
    outputs = layers.fully_connected(inputs=X_for_fc,
                                                   num_outputs=output_size,
                                                   activation_fn=None)
    # reshape outputs for sequence_loss
    outputs = tf.reshape(outputs, [batch_size, sequence_length, output_size])
    
    FC_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope='RNN')

with tf.variable_scope("loss"):
    weights = tf.ones([batch_size, sequence_length]) 
    sequence_loss = tf.contrib.seq2seq.sequence_loss(logits=outputs,
                                                                                 targets=Y,
                                                                                 weights=weights)
    loss = tf.reduce_mean(sequence_loss)
    train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss, var_list=FC_vars)
    tf.summary.scalar("loss", loss)
    
prediction = tf.argmax(outputs, axis=2)

### Train the model

In [6]:
step = 1000
with tf.Session() as sess:
    writer = tf.summary.FileWriter("./graphs/rnn", sess.graph)
    summary_op = tf.summary.merge_all()
    sess.run(tf.global_variables_initializer())
    
    print("y: ", train_melody[1: ])
    for i in range(step):
        loss_val, _ = sess.run([loss, train], feed_dict={X:x_data, Y:y_data})
        result = sess.run(prediction, feed_dict={X:x_data})
        
        summary = sess.run(summary_op, feed_dict={X:x_data, Y:y_data})
        
        result_str = [idx2char[c] for c in np.squeeze(result)]
        error = np.array(result_str) - np.array(train_melody[1:])
        
        print( "{:4d}  loss: {:.5f}".format(i, loss_val), "    Prediction: ", result_str, "    error: ", error)
        
        writer.add_summary(summary, i)

y:  [2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 3, 1, 2, 2, 2, 2, 4, 3, 1, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 8, 2, 2, 2, 2, 4, 3, 1, 2, 2, 2, 2, 4, 3, 1, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 6, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2]
   0  loss: 3.62908     Prediction:  [33, 33, 33, 33, 16, 33, 33, 16, 16, 33, 33, 33, 33, 33, 16, 2, 33, 16, 16, 2, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 28, 2, 2, 33, 33, 33, 33, 28, 2, 2, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 28, 2, 13, 13, 13, 13, 33, 28, 35, 13, 13, 13, 33, 33, 16, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 2, 2, 13, 13, 13, 33, 33, 28, 35, 13, 13, 13, 33, 33, 16, 33, 33, 33, 33, 33, 33, 33, 33, 28, 28, 28, 28, 16, 16, 16, 16, 33, 16, 16, 16, 33, 33, 33, 3